services:
  backend:
    build: ./project/backend
    ports:
      - "8000:8000"
  frontend:
    build: ./project/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://193.196.53.179:8000
      - VITE_WS_URL=ws://193.196.53.179:8000
